### ISSUE TITLE
little help needed poolworker

### ISSUE THREAD

**Issue by 49handyman** [s-nomp/s-nomp#172]
2021-02-13 20:13:30 [Master]    [PoolSpawner] Fork 1 died, spawning replacement worker...
2021-02-13 20:13:32 [Switching] [Setup] (Thread 2) Loading last proxy state from redis
2021-02-13 20:13:32 [Pool]      [komodo] (Thread 2) Share processing setup with redis (127.0.0.1:6379)
2021-02-13 20:13:32 [Switching] [Setup] (Thread 2) Switching "switch1" listening for equihash on port 3333 into komodo
2021-02-13 20:13:33 [Pool]      [komodo] (Thread 2) getblocktemplate call failed for daemon instance 0 with error {"code":-9,"message":"Cannot get a block template while no peers are connected or chain not in sync!"}
2021-02-13 20:13:33 [Pool]      [komodo] (Thread 2) Error with getblocktemplate on creating first job, server cannot start
2021-02-13 20:13:35 [Switching] [Connect] (Thread 3) Connection to switch1 from ::ffff:136.32.180.78 on 3333 routing to komodo
/home/ubuntu/s-nomp/libs/poolWorker.js:273
                            pools[currentPool].getStratumServer().handleNewClient(socket);
                                                                 ^

TypeError: Cannot read property 'handleNewClient' of undefined
    at Server.<anonymous> (/home/ubuntu/s-nomp/libs/poolWorker.js:273:66)
    at Server.emit (events.js:198:13)
    at Object.onconnection (net.js:1520:8)
    at onconnection (internal/cluster/child.js:183:12)
    at Worker.onmessage (internal/cluster/child.js:45:7)
    at process.onInternalMessage (internal/cluster/utils.js:45:8)
    at process.emit (events.js:203:15)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by 49handyman** [comment]
As I thought pool won't start and open port until the full node blockchain is synced

**Comment by zzzpotato** [comment]
What version of node and nodejs are you using?

**Comment by zzzpotato** [comment]
> What version of node and nodejs are you using?

I just realized you are trying to run komodo. I don't believe s-nomp is compatible. Please look at k-nomp

**Comment by 49handyman** [comment]
yes, thanks finally figured that out.. lol

looks like it its the /node-stratum-pool.git versions

got webworkers01's workers working on new ubuntu 18 machine. also had problems with env. node 10.14.2 worked best for me.
