### ISSUE TITLE
Using Docker-Compose, S-Nomp site container dies shortly after init

### ISSUE THREAD

**Issue by julazcano** [s-nomp/s-nomp#179]
I spawned the redis and site nodes using the compose file successfully.  However, when I check on the status of the containers, only redis is alive.  So when I check the runtime logs of the site node, I see a recurring error regarding the async module that is missing for some reason.  See the excerpts:

###
###

Step 6/6 : CMD ["pm2-runtime", "start", "ecosystem.config.js", "--only", "site"]
 ---> Running in e5b42b3cadbf
Removing intermediate container e5b42b3cadbf
 ---> 707c73764adc
Successfully built 707c73764adc
Successfully tagged s-nomp_site:latest
WARNING: Image for service site was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Pulling redis (redis:latest)...
latest: Pulling from library/redis
a2abf6c4d29d: Pull complete
c7a4e4382001: Pull complete
4044b9ba67c9: Pull complete
c8388a79482f: Pull complete
413c8bb60be2: Pull complete
1abfd3011519: Pull complete
Digest: sha256:db485f2e245b5b3329fdc7eff4eb00f913e09d8feb9ca720788059fdc2ed8339
Status: Downloaded newer image for redis:latest
Creating s-nomp_site_1  ... done
Creating s-nomp_redis_1 ... done

###
###
2021-12-29T06:41:40: PM2 log: App [site:0] starting in -fork mode-
2021-12-29T06:41:40: PM2 log: App [site:0] online
{ Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:548:15)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/site/init.js:6:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerForkLegacy.js:28:21) code: 'MODULE_NOT_FOUND' }
2021-12-29T06:41:40: PM2 log: App [site:0] exited with code [1] via signal [SIGINT]
2021-12-29T06:41:40: PM2 log: Script /site/init.js had too many unstable restarts (16). Stopped. "errored"
2021-12-29T06:41:44: PM2 log: 0 application online, retry = 3
2021-12-29T06:41:46: PM2 log: 0 application online, retry = 2
2021-12-29T06:41:48: PM2 log: 0 application online, retry = 1
2021-12-29T06:41:50: PM2 log: 0 application online, retry = 0
2021-12-29T06:41:50: PM2 log: Stopping app:site id:0
2021-12-29T06:41:50: PM2 error: app=site id=0 does not have a pid
2021-12-29T06:41:50: PM2 log: PM2 successfully stopped

Any thoughts?

**Comment by interbiznw** [comment]
You need to do npm install in the repo root directory

**Comment by interbiznw** [comment]
the docker compose is using the code from the ./ dir, mounting it to /site
i.e.
```    
volumes:
    - ./:/site

```

meaning the project root, and starts ecosystem.config.js, which in turn runs init.js, which is not setup/installed in the container so there are no node dependencies for it. Meaning they need to also be installed in the root of the project FIRST

So when docker runs it, everything is there

So just make sure you have the right version of node installed, then run `npm update`, and then `npm install`, 

THEN  run `docker-compose up`

**Comment by julazcano** [comment]
Thanks for the help guys - makes a lot of sense.  Will report back once I'm all set and close it down.

**Comment by julazcano** [comment]
Odd - still having similar issue.  I've verified that I followed all the npm build tasks with nvm correctly because I can spawn the web-server with pm2 normally.  But when i build with docker-compose, although the container has pulled in all the node_modules and config files from the root directory, there is still some error being thrown that causes it to keep crashing.  I'm running NPM 8.17.0 via nvm as per the discord chat.  

/s-nomp$ docker logs d0e557731ac1
2022-01-18T14:52:54: PM2 log: Launching in no daemon mode
2022-01-18T14:52:54: PM2 log: App [site:0] starting in -fork mode-
2022-01-18T14:52:54: PM2 log: App [site:0] online
Error: libsodium.so.23: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
    at require (internal/module.js:11:18)
    at bindings (/site/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/site/node_modules/equihashverify/index.js:1:99)
    at Module._compile (module.js:653:30)
2022-01-18T14:52:54: PM2 log: App [site:0] exited with code [1] via signal [SIGINT]
2022-01-18T14:52:54: PM2 log: App [site:0] starting in -fork mode-
2022-01-18T14:52:54: PM2 log: App [site:0] online
Error: libsodium.so.23: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
    at require (internal/module.js:11:18)
    at bindings (/site/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/site/node_modules/equihashverify/index.js:1:99)
    at Module._compile (module.js:653:30)
2022-01-18T14:52:54: PM2 log: App [site:0] exited with code [1] via signal [SIGINT]
2022-01-18T14:52:54: PM2 log: App [site:0] starting in -fork mode-
2022-01-18T14:52:54: PM2 log: App [site:0] online

**Comment by julazcano** [comment]
quick google search came up with an interesting hit:

https://forum.cardano.org/t/error-while-loading-shared-libraries-libsodium-so-23/55495/5
In the forum, it shows a solution to a similar problem by creating a symlink for libsodium.so.23.  
Would this need to be set within the Dockerfile?  Or where?
