### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by david739** [s-nomp/s-nomp#194]
hello, I will install it, but when I start the pool, it gives me this error, does anyone know what to do with it?

/home/pool/pool/node_modules/stratum-pool/lib/algoProperties.js:30
            let parameters = coinOptions.parameters
            ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/pool/pool/node_modules/stratum-pool/lib/index.js:5:1)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)

**Comment by zzzpotato** [comment]
What node version?

**Comment by david739** [comment]
hello, I have already solved it, could you please advise me on the settings on bch

**Comment by david739** [comment]
hello, now that I have everything set up, I start btc but with bch there is this error

/home/pool/pool/node_modules/bignum/index.js:97
      throw new TypeError('Unspecified operation for type ' +
      ^

TypeError: Unspecified operation for type undefined for add
    at BigNum.(anonymous function) [as add] (/home/pool/pool/node_modules/bignum/index.js:97:13)
    at Object.base58.decode (/home/pool/pool/node_modules/stratum-pool/node_modules/base58-native/base58.js:49:23)
    at Object.exports.addressToScript (/home/pool/pool/node_modules/stratum-pool/lib/util.js:266:26)
    at /home/pool/pool/node_modules/stratum-pool/lib/pool.js:426:37
    at /home/pool/pool/node_modules/stratum-pool/lib/pool.js:428:15
    at /home/pool/pool/node_modules/stratum-pool/lib/daemon.js:134:13
    at parseJson (/home/pool/pool/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/pool/pool/node_modules/stratum-pool/lib/daemon.js:95:17)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
2022-08-05 13:29:02 [Master]    [PoolSpawner] Fork 5 died, spawning replacement worker...
^C

**Comment by zzzpotato** [comment]
bch/btc is not supported. s-nomp is for zcash forks
