### ISSUE TITLE
TypeError: Expected String

### ISSUE THREAD

**Issue by Jerry170617** [s-nomp/s-nomp#65]
/home/pool/snomp/node_modules/bitcoinjs-lib-zcash/node_modules/base-x/index.js:52
    if (typeof string !== 'string') throw new TypeError('Expected String')
                                    ^

TypeError: Expected String
    at decodeUnsafe (/home/pool/snomp/node_modules/bitcoinjs-lib-zcash/node_modules/base-x/index.js:52:43)
    at Object.decode (/home/pool/snomp/node_modules/bitcoinjs-lib-zcash/node_modules/base-x/index.js:81:18)
    at Object.decode (/home/pool/snomp/node_modules/bitcoinjs-lib-zcash/node_modules/bs58check/base.js:39:25)
    at Object.fromBase58Check (/home/pool/snomp/node_modules/bitcoinjs-lib-zcash/src/address.js:11:27)
    at Object.exports.createGeneration (/home/pool/snomp/node_modules/stratum-pool/lib/transactions.js:133:56)
    at new BlockTemplate (/home/pool/snomp/node_modules/stratum-pool/lib/blockTemplate.js:59:35)
    at JobManager.processTemplate (/home/pool/snomp/node_modules/stratum-pool/lib/jobManager.js:155:32)
    at /home/pool/snomp/node_modules/stratum-pool/lib/pool.js:601:66
    at itemFinished (/home/pool/snomp/node_modules/stratum-pool/lib/daemon.js:166:36)
    at /home/pool/snomp/node_modules/stratum-pool/lib/daemon.js:180:17

**Comment by egyptianbman** [comment]
What version of nodejs are you using?

**Comment by zheng9980419** [comment]
v4.2.6
Recommended version?

**Comment by Jerry170617** [comment]
Recommended version?

**Comment by Jerry170617** [comment]
@egyptianbman

**Comment by egyptianbman** [comment]
The recommended version is in the readme as well as the package.json. Again, please don't create issues unless you find bugs in the code. Use discord, thanks.

**Comment by Jerry170617** [comment]
@egyptianbman The current version is v8.11.4

**Comment by Jerry170617** [comment]
pool@iZbp15cl1s1akgbox83su8Z:~$ node -v
v8.11.4
pool@iZbp15cl1s1akgbox83su8Z:~$ npm -v
5.6.0
